# Generated by Django 5.1.4 on 2024-12-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrarianAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
